'use strict';

// Every pair is [real question, imposter question]. Both must lead to the same
// kind of answer, so the imposter's answer looks plausible but slightly off.

const TOPICS = [
  { id: 'food', name: 'Food and drink', emoji: '🍕' },
  { id: 'money', name: 'Money', emoji: '💸' },
  { id: 'dating', name: 'Dating and relationships', emoji: '💘' },
  { id: 'sport', name: 'Sport', emoji: '⚽' },
  { id: 'work', name: 'Work and school', emoji: '💼' },
  { id: 'travel', name: 'Travel', emoji: '✈️' },
  { id: 'screen', name: 'Film, TV and music', emoji: '🎬' },
  { id: 'numbers', name: 'Numbers and guesses', emoji: '🔢' },
  { id: 'hot', name: 'Hot takes', emoji: '🌶️' },
  // Answered by picking a player in the room.
  { id: 'group', name: 'This group', emoji: '👀', answerType: 'player' },
];

const BANK = {
  food: [
    ['What is the best pizza topping?', 'What is your favourite vegetable?'],
    ['What is the best midnight snack?', 'What is the best breakfast food?'],
    ['What do you order at a bar?', 'What do you drink first thing in the morning?'],
    ['What food could you eat every single day?', 'What food do you only eat on holiday?'],
    ['What is the best ice cream flavour?', 'What is the best flavour of cake?'],
    ['What do you put on toast?', 'What do you put on a burger?'],
    ['What do you eat at the cinema?', 'What do you eat on a long car journey?'],
    ['What is the best hangover food?', 'What is the best thing to cook on a barbecue?'],
    ['What fruit is overrated?', 'What fruit would you bring to a picnic?'],
    ['What is your go-to takeaway?', 'What would you cook to impress a date?'],
    ['What drink makes you feel fancy?', 'What drink reminds you of being a teenager?'],
    ['What is the best sandwich filling?', 'What is the best thing to put in an omelette?'],
    ['What snack do you grab at a petrol station?', 'What snack do you bring on a hike?'],
    ['What food is not worth the effort to cook?', 'What do you always order at a restaurant?'],
    ['What is the best soup?', 'What do you eat when you are ill?'],
    ['What makes a salad better?', 'What makes a pizza better?'],
    ['What is the most overrated food?', 'What is the fanciest food you have ever eaten?'],
    ['What is the best thing to dip fries in?', 'What is the best sauce for a burger?'],
    ['What would your last meal be?', 'What is the best meal your family makes?'],
    ['What is the best hot drink?', 'What do you drink when you are sad?'],
    ['What food would you ban forever?', 'What food smells the worst?'],
    ['What food did you hate as a kid?', 'What food do you pretend to like?'],
  ],

  money: [
    ['How much would you pay for a great haircut?', 'How much would you pay for a great pizza?'],
    ['What is the most you would spend on a pair of shoes?', 'What is the most you would spend on a pair of jeans?'],
    ['What would you buy first if you won the lottery?', 'What is the most expensive thing you own?'],
    ['How much cash is in your wallet right now?', 'How much would you tip after a fancy dinner?'],
    ['How much money would make you quit your job tomorrow?', 'How much would you pay to never do chores again?'],
    ['What is the most you would pay for a concert ticket?', 'What is the most you would spend on a birthday present for a friend?'],
    ['What do you waste the most money on?', 'What do you refuse to spend money on?'],
    ['What is a fair price for a cup of coffee?', 'What is a fair price for a beer?'],
    ['How much would someone have to pay you to eat a worm?', 'How much would someone have to pay you to shave your head?'],
    ['How much pocket money should a 10-year-old get per week?', 'How much should the tooth fairy pay per tooth?'],
    ['What is the best cheap thing you ever bought?', 'What is the worst thing you ever wasted money on?'],
    ['What would you splash out on for a perfect weekend?', 'What would you cut first if you were broke?'],
    ['What subscription is actually worth the money?', 'What subscription do you keep forgetting to cancel?'],
    ['How much would you pay to skip every queue for life?', 'How much would you pay for one extra hour of sleep every day?'],
    ['What is the most you have spent on a night out?', 'What is the most you have spent on a single meal?'],
    ['How much would you lend a friend without expecting it back?', 'How much would you bet on yourself in a game of bowling?'],
    ['What job is paid too much?', 'What job would you do if money did not matter?'],
    ['How much should a wedding cost?', 'How much should a first car cost?'],
    ['What would you sell first if you needed money fast?', 'What was your last impulse buy?'],
    ['What shop could you spend all your money in?', 'What shop do you avoid because it is too expensive?'],
    ['How much is too much for a bottle of wine?', 'How much is too much for a T-shirt?'],
    ['At what age do you want to retire?', 'At what age do people have the most money?'],
  ],

  dating: [
    ['What is the perfect first date?', 'What is the worst idea for a first date?'],
    ['What is the biggest red flag?', 'What is your most annoying habit?'],
    ['How many dates before you meet the parents?', 'How many dates before the first kiss?'],
    ['What is the most attractive hobby?', 'What hobby is an instant turn-off?'],
    ['What is the best pet name for a partner?', 'What is the best name for a dog?'],
    ['What is the ideal age to get married?', 'What is the ideal age to move in together?'],
    ['What song sets the mood?', 'What song would you play at a wedding?'],
    ['Where is the best place to meet someone?', 'Where is the worst place to get dumped?'],
    ['What is the most romantic city?', 'What city is best for a wild weekend with friends?'],
    ['What job makes someone more attractive?', 'What job would you not want your partner to have?'],
    ['What gift saves you when you forgot the anniversary?', 'What gift do you give your mum?'],
    ['What is the best film for date night?', 'What film makes you cry?'],
    ['How many minutes should you wait before texting back?', 'How many minutes is too long to spend getting ready?'],
    ['What is the best food for a first date?', 'What food should you never eat on a first date?'],
    ['Which celebrity is your hall pass?', 'Which celebrity would you want as a best friend?'],
    ['What matters most in a partner?', 'What matters most in a boss?'],
    ['How many exes is too many?', 'How many first dates in one month is too many?'],
    ['What do you notice first about someone?', 'What do people notice first about you?'],
    ['What is the best excuse to leave a bad date?', 'What is the best excuse to skip work?'],
    ['Where is the best place to propose?', 'Where is the best place for a honeymoon?'],
    ['What would you cook for a date?', 'What do you cook when you are home alone?'],
    ['What drink do you order on a first date?', 'What drink do you order after a breakup?'],
  ],

  sport: [
    ['What sport is the most boring to watch?', 'What sport would you be worst at?'],
    ['What sport would you compete in at the Olympics?', 'What sport should be kicked out of the Olympics?'],
    ['How many push-ups can you do in a row?', 'How many minutes can you run without stopping?'],
    ['Who is the greatest athlete of all time?', 'Who is the most famous athlete alive?'],
    ['What is the best sport to play on a beach?', 'What is the best sport to play after a few drinks?'],
    ['How many kilometres could you walk in one day?', 'How many kilometres could you cycle in one day?'],
    ['What sport has the fittest athletes?', 'What sport has the best-looking athletes?'],
    ['What is the best snack at a stadium?', 'What is the best snack after a workout?'],
    ['What sport do you secretly think is easy?', 'What sport did you quit as a kid?'],
    ['How many hours of sport do you watch a week?', 'How many hours do you exercise a week?'],
    ['Which team has the most annoying fans?', 'Which team would you support if you had to start over?'],
    ['What is the most dangerous sport?', 'What sport would you never let your kid try?'],
    ['How many seconds would it take you to run 100 metres?', 'How many seconds can you hold a plank?'],
    ['What sport has the best outfits?', 'What sport has the worst outfits?'],
    ['What would be your walk-out song?', 'What song gets you through a workout?'],
    ['What sport would you pay to watch live?', 'What sport would you only watch if someone paid you?'],
    ['What was the best game in school PE?', 'What school PE game caused the most injuries?'],
    ['How many goals would you score against a team of 10-year-olds?', 'How many 10-year-olds could you beat in a tug of war?'],
    ['What animal would be best at football?', 'What animal would win a 100 metre sprint?'],
    ['What country is the best at sport?', 'What country has the best football team?'],
    ['What is the best sport to watch in a pub?', 'What is the best sport to watch at 3am?'],
    ['What sport needs the most brains?', 'What sport needs the least skill?'],
  ],

  work: [
    ['What was your best subject at school?', 'What was your worst subject at school?'],
    ['What job did you want as a kid?', 'What job would you be terrible at?'],
    ['How many hours of real work do you do in a day?', 'How many coffee breaks do you take in a day?'],
    ['What is the best excuse for being late?', 'What is the best excuse for missing homework?'],
    ['What is the worst thing about meetings?', 'What is the worst thing about group projects?'],
    ['How many unread emails do you have?', 'How many browser tabs do you have open right now?'],
    ['What is the best day to work from home?', 'What is the worst day of the week?'],
    ['What job deserves a pay rise?', 'What job looks like the most fun?'],
    ['What time should the work day start?', 'What time do you actually wake up?'],
    ['What do you do when the boss is not looking?', 'What did you do when the teacher left the room?'],
    ['What is the most useless thing you learned at school?', 'What is the most useful thing you learned at school?'],
    ['What snack lives in your desk drawer?', 'What was always in your school lunchbox?'],
    ['How many sick days a year is it fair to fake?', 'How many weeks of holiday should everyone get?'],
    ['What job will robots take first?', 'What job could you do half asleep?'],
    ['What is the most annoying office habit?', 'What is the most annoying classroom habit?'],
    ['What would you wear to work if there were no rules?', 'What do you wear on a lazy Sunday?'],
    ['At what age did you get your first job?', 'At what age did you first skip a class?'],
    ['Which subject had the scariest teacher?', 'Which subject had the coolest teacher?'],
    ['What app do you open when you should be working?', 'What app do you use the most for work?'],
    ['How many minutes late still counts as on time?', 'How many minutes is the perfect lunch break?'],
    ['What word do you overuse in emails?', 'What word did you overuse in school essays?'],
    ['What is the best thing to do on a lunch break?', 'What is the best thing to do on a sick day?'],
  ],

  travel: [
    ['What country do you most want to visit?', 'What country has the best food?'],
    ['What is the first thing you pack?', 'What do you always forget to pack?'],
    ['What city is overrated?', 'What city would you move to tomorrow?'],
    ['How many hours is too long for a flight?', 'How many hours is too long for a road trip?'],
    ['What is the best thing to do on a plane?', 'What is the best thing to do on a rainy holiday?'],
    ['What country has the friendliest people?', 'What country has the best-looking people?'],
    ['Where is the worst place to be stuck for a day?', 'What is the most boring place you have ever visited?'],
    ['How many countries have you been to?', 'How many countries can you name in 30 seconds?'],
    ['What souvenir do you always buy?', 'What is the worst gift to bring back from a holiday?'],
    ['What language would you love to speak?', 'What language sounds the angriest?'],
    ['What is the best seat on a plane?', 'What is the best seat in a car?'],
    ['How many days is the perfect holiday?', 'How many days can you travel with family before you snap?'],
    ['What is the best holiday activity?', 'What holiday activity is a total tourist trap?'],
    ['What city has the best nightlife?', 'What city has the worst weather?'],
    ['What do you miss most when you are away?', 'What is the first thing you do when you get home from a trip?'],
    ['What would you bring to a desert island?', 'What would you grab if your hotel was on fire?'],
    ['What is the best way to travel?', 'What is the worst way to travel?'],
    ['What country would you never go back to?', 'What country do you know the least about?'],
    ['How many kilos of luggage do you take for a weekend?', 'How many pairs of shoes do you pack for a week?'],
    ['What is the best beach snack?', 'What is the best airport snack?'],
    ['Where would you go for a year off?', 'Where would you go to disappear forever?'],
    ['What is the most beautiful place you have been?', 'Where was your worst holiday?'],
  ],

  screen: [
    ['What film have you seen the most times?', 'What film do you pretend to have seen?'],
    ['What is the best TV show ever?', 'What TV show went on for too long?'],
    ['What song do you sing in the shower?', 'What song do you pick at karaoke?'],
    ['Who was the first artist you saw live?', 'Which artist would you pay the most to see live?'],
    ['Which actor should play you in a film?', 'Which actor would you want as a neighbour?'],
    ['What film scared you as a kid?', 'What film do you watch every Christmas?'],
    ['What song always fills the dance floor?', 'What song should be banned from weddings?'],
    ['Which cartoon character is the funniest?', 'Which cartoon character would you want as a flatmate?'],
    ['How many hours of TV do you watch a day?', 'How many episodes count as a proper binge?'],
    ['What band should get back together?', 'What band is overrated?'],
    ['Which film villain is the scariest?', 'Which film villain was actually right?'],
    ['What reality show would you win?', 'What reality show is your guilty pleasure?'],
    ['What film has the best soundtrack?', 'What film has the best ending?'],
    ['What instrument is the coolest?', 'What instrument is the most annoying?'],
    ['What decade had the best music?', 'What decade had the best fashion?'],
    ['Which TV character would you date?', 'Which TV character would you trust with a secret?'],
    ['Which superhero is the best?', 'Which superhero is the most useless?'],
    ['What film would you show to an alien?', 'What film is everyone wrong about?'],
    ['What TV theme tune can you hum perfectly?', 'What TV show did you love as a kid?'],
    ['How many times have you seen your favourite film?', 'How many films do you watch in a month?'],
    ['Which singer has the best voice?', 'Which singer has the best outfits?'],
    ['What film genre is best for a night in?', 'What film genre should be banned on planes?'],
  ],

  numbers: [
    ['How many hours of sleep do you need?', 'How many hours a day are you on your phone?'],
    ['How many slices of pizza can you eat in one sitting?', 'How many cups of coffee or tea do you drink a day?'],
    ['How many countries are there in Europe?', 'How many countries are there in Africa?'],
    ['How tall is a giraffe in metres?', 'How long is a bus in metres?'],
    ['How many five-year-olds could you take in a fight?', 'How many geese could you take in a fight?'],
    ['How many days could you survive without your phone?', 'How many days could you survive in the wild?'],
    ['What is the perfect age to be?', 'At what age are you officially old?'],
    ['How many times do you hit snooze?', 'How many alarms do you set in the morning?'],
    ['How many friends would help you move house?', 'How many people do you text every day?'],
    ['How many minutes is the perfect shower?', 'How many minutes does it take you to get ready in the morning?'],
    ['How many kilos does a lion weigh?', 'How many kilos does a pig weigh?'],
    ['How many books did you read last year?', 'How many films did you watch last year?'],
    ['How many pairs of shoes do you own?', 'How many pairs of trousers do you own?'],
    ['How many photos are on your phone?', 'How many songs are in your biggest playlist?'],
    ['How many steps do you walk on a normal day?', 'How many steps does it take to burn off a burger?'],
    ['How many seconds can you hold your breath?', 'How many seconds can you stand on one leg with your eyes closed?'],
    ['What year would you travel back to?', 'What was the best year of your life?'],
    ['How many hot dogs could you eat in 10 minutes?', 'How many pancakes could you eat for breakfast?'],
    ['How many bones are in the human body?', 'How many teeth does a shark have?'],
    ['From 1 to 10, how good a driver are you?', 'From 1 to 10, how good a cook are you?'],
    ['How many keys are on your keyring?', 'How many cards are in your wallet?'],
    ['How many minutes of silence before it gets awkward?', 'How many minutes late are you usually?'],
    ['What percentage is your phone battery at right now?', 'At what battery percentage do you start to panic?'],
  ],

  hot: [
    ['What is the most overrated holiday of the year?', 'What is the best holiday of the year?'],
    ['What popular food is actually disgusting?', 'What weird food is actually delicious?'],
    ['What app should be deleted from the world?', 'What app could you not live without?'],
    ['What chore is the worst?', 'What chore is secretly satisfying?'],
    ['What animal is overrated?', 'What animal would make the worst pet?'],
    ['What fashion trend needs to die?', 'What fashion trend should come back?'],
    ['What is the worst month of the year?', 'What is the best month of the year?'],
    ['What word or phrase should be banned?', 'What word do you say way too much?'],
    ['What is the most useless thing in your home?', 'What is the most used thing in your home?'],
    ['What sport is not really a sport?', 'What hobby is just an excuse to buy stuff?'],
    ['What is the worst age to be?', 'At what age do you stop being cool?'],
    ['What breakfast is really just dessert?', 'What dessert is not worth the calories?'],
    ['What social media is the worst?', 'What social media will die next?'],
    ['What is the most overrated drink?', 'What drink is only for old people?'],
    ['What is the worst pizza topping?', 'What should never go in a salad?'],
    ['Which famous person is overrated?', 'Which famous person would you hate to be stuck in a lift with?'],
    ['What time is too early to wake up?', 'What time is too late to call someone?'],
    ['What is the worst kind of weather?', 'What weather is best for staying in bed?'],
    ['What should be free for everyone?', 'What should cost twice as much?'],
    ['What is the best smell in the world?', 'What smell do you love that other people hate?'],
    ['What is the most annoying sound?', 'What sound wakes you up in the morning?'],
    ['What hobby is the most boring?', 'What hobby do you wish you were good at?'],
    ['What vegetable is pointless?', 'What vegetable is the king of vegetables?'],
  ],

  group: [
    ['Who would survive longest on a desert island?', 'Who would die first in a horror film?'],
    ['Who is most likely to become famous?', 'Who is most likely to end up in jail?'],
    ['Who would you call at 3am in an emergency?', 'Who would you call to help hide a body?'],
    ['Who is the worst driver?', 'Who is most likely to get lost?'],
    ['Who takes the longest to get ready?', 'Who is always late?'],
    ['Who would win in a fight?', 'Who would win a shouting match?'],
    ['Who is the best cook?', 'Who eats the most?'],
    ['Who is the funniest?', 'Who laughs the loudest?'],
    ['Who would do best on a quiz show?', 'Who would do best on a reality show?'],
    ['Who spends the most money?', 'Who is most likely to become a millionaire?'],
    ['Who would you trust with a secret?', 'Who would you trust with your unlocked phone?'],
    ['Who is the biggest flirt?', 'Who gives the best love advice?'],
    ['Who is the most competitive?', 'Who is the worst loser?'],
    ['Who would make the best boss?', 'Who would make the best teacher?'],
    ['Who is most likely to cry at a film?', 'Who is most likely to fall asleep during a film?'],
    ['Who has the best taste in music?', 'Who would you let choose the film?'],
    ['Who is most likely to move abroad?', 'Who is most likely to never leave their home town?'],
    ['Who would last longest without their phone?', 'Who is on their phone the most?'],
    ['Who is most likely to text their ex?', 'Who is most likely to reply three days late?'],
    ['Who would you want on your team in a zombie apocalypse?', 'Who would be the first to become a zombie?'],
    ['Who has the best style?', 'Who takes the most selfies?'],
    ['Who tells the worst jokes?', 'Who talks the most?'],
    ['Who is the best liar?', 'Who is the worst at keeping secrets?'],
  ],
};

const PAIRS = TOPICS.flatMap((topic) =>
  BANK[topic.id].map(([real, imposter], index) => ({
    id: `${topic.id}-${index + 1}`,
    topic: topic.id,
    real,
    imposter,
    answerType: topic.answerType || 'text',
  }))
);

module.exports = { TOPICS, PAIRS };
